### ISSUE TITLE
bluetooth beacons

### ISSUE THREAD

**Issue by substack** [mozilla/libdweb#10]
There is a huge opportunity to implement p2p gossip protocols in an offline setting using webbluetooth. With bluetooth, devices don't need to be connected to the same wifi network in order to use mdns and tcp or udp for discovery and transmission.

Unfortunately, beacon support for webbluetooth is stalled at the moment: https://github.com/WebBluetoothCG/web-bluetooth/issues/231#issuecomment-334887136

But maybe highlighting offline p2p use cases can help get more attention for bluetooth beacon support?

**Comment by Gozala** [comment]
@substack I think having Bluetooth support would be excellent. Unfortunately I also found out that Mozilla had some concerns with WebBluetooth spec, I don't exactly know what the problems are though

@autonome you mentioned something about the thread with public statements about this, do you have a pointer so we can digg into what the issues are and figure out if they are solvable ?

**Comment by rjsteinert** [comment]
I'm particularly interested in this feature in order to allow P2P offline sync of PouchDB databases for the sake of keeping medical records in sync across devices in rural Africa.

**Comment by autonome** [comment]
Thanks @rjsteinert! Do you have a link to that work? I know a project (also in Africa!) which has a use-case for which that exact scenario could be very helpful.

@Gozala, Mozilla's public statement on WebBluetooth is here: https://github.com/mozilla/standards-positions/issues/95

**Comment by rjsteinert** [comment]
Hi @autonome - We (Research Triangle Institute) don't have any articles describing the work yet, launch date is looking like some time in October. We're currently building a case management solution into [Tangerine](https://github.com/tangerine-community/tangerine) along with this P2P offline PouchDB sync over Wifi Direct for Android. However we're not so sure the Wifi Direct option is going to pan out, [other projects such as Microsoft funded Thali](http://thaliproject.org) have [tried](http://www.drjukka.com/blog/wordpress/?p=52) but appear to have abandoned it.

**Comment by Gozala** [comment]
I would love this but I'm afraid it's unrealistic to get it out without a larger Firefox support. Closing this issue in an effort to migrate issues to bugzilla & code into gecko.
