### ISSUE TITLE
Security Error: Content at moz-nullprincipal:{<id>} may not load or link to <url>

### ISSUE THREAD

**Issue by tom-james-watson** [mozilla/libdweb#102]
Hello,

I have been working on an extension that uses libdweb to load websites using webtorrent - https://github.com/tom-james-watson/wtp-ext/, using a `wtp://` protocol handler.

I have it all working successfully again after updating to the latest libdweb version, apart from one issue. For some reason, I can no longer click on hyperlinks to `wtp://` URLs from pages that are being handled by my extension.

For example, on [wtp://951ead31d09e4049fc1f21f137e233dd0589fcbd](wtp://951ead31d09e4049fc1f21f137e233dd0589fcbd), I cannot click on a hyperlink to [wtp://951ead31d09e4049fc1f21f137e233dd0589fcbd/blog/](wtp://951ead31d09e4049fc1f21f137e233dd0589fcbd/blog/).

The browser console is throwing the following error:

```
Security Error: Content at moz-nullprincipal:{d58df534-8c48-4658-9db9-27889f353508} may not load or link to wtp://951ead31d09e4049fc1f21f137e233dd0589fcbd/blog/.
```

This did actually previously work with an older version of firefox and libdweb. Is this a bug? Is there something I'm potentially missing from [my manifest.json](https://github.com/tom-james-watson/wtp-ext/blob/master/extension/manifest.json), for example?

**Comment by Gozala** [comment]
@tom-james-watson I think this should be addressed by https://phabricator.services.mozilla.com/D39463 and be available on nightly. If it is not please reopen.

**Comment by cowwoc** [comment]
@Gozala Which release (non-nightly) will this show up in? I am getting this error all the time.

The exact error message is:

`Security Error: Content at moz-nullprincipal:{d452c7e0-3ad7-4b3f-9034-f874de37cde2} may not load or link to imap://gili%2Etzabari%40gmail%2Ecom@imap.gmail.com:993/fetch%3EUID%3E/%5BGmail%5D/Drafts%3E19355?part=1.2&filename=image001.png.`
