### ISSUE TITLE
Can't supply page_action pattern with registered protocol

### ISSUE THREAD

**Issue by tom-james-watson** [mozilla/libdweb#103]
I have a custom `wtp://` protocol handler, however if I try to add add a `page_action` with a pattern for my protocol:

```
  "page_action": {
    ...
    "show_matches": ["wtp://*"]
  }
```

I receive the following error:

```
Error processing page_action.show_matches.0: Value "wtp://*" must either: be one of ["<all_urls>"], must either [match the pattern /^(https?|wss?|file|ftp|\*):\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$/, or match the pattern /^file:\/\/\/.*$/], or match the pattern /^resource:\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$|^about:/
```

If we can add custom protocols then it would make sense to be able to do this.

**Comment by sammacbeth** [comment]
This is related to #26 - extensions APIs do not understand non `http(s)` URLs, so all that use this matching syntax will not work.

In this case there is a work around: You can still see the custom protocol URLs in the `tabs` API and trigger the page action from there:
```javascript
browser.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {
  if (tab.url && tab.url.startsWith('wtp://')) {
    browser.pageAction.show(tabId);
  } else {
    browser.pageAction.hide(tabId);
  }
});
```
See also: https://github.com/cliqz-oss/dat-webext/blob/b3893055da211c508078e0790fa901b2c0638460/background/index.ts#L71

**Comment by tom-james-watson** [comment]
Thanks, Sam. In the end I did something similar - in the request handler I grab the current tab and `browser.pageAction.show(tabId);` from there.

**Comment by Gozala** [comment]
Filled a bug in bugzilla for this  https://bugzilla.mozilla.org/show_bug.cgi?id=1572187 as this can't be addressed here.
