### ISSUE TITLE
Cannot call browser.tabs.create with a URL with protocol handled by extension

### ISSUE THREAD

**Issue by tom-james-watson** [mozilla/libdweb#104]
I'm trying to programmatically open a tab from my extension with a URL that has a protocol which is handled by the extension:

```
browser.tabs.create({'url': `wtp://<URL>`)
```

However I receive the following error:

```
Error: Illegal URL: wtp://<URL>
```

It doesn't make sense for the URL to be treated as illegal if the extension has permission to handle requests on that protocol.

**Comment by Gozala** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1572230 as it needs to be addressed at the tabs API
