### ISSUE TITLE
Omitting contentType in browser.protocol.registerProtocol crashes nightly

### ISSUE THREAD

**Issue by lidel** [mozilla/libdweb#20]
I've been experimenting with Protocol handler API (https://github.com/mozilla/libdweb/issues/2) and tried to follow suggestion from https://github.com/mozilla/libdweb/issues/2#issuecomment-395583221:

>> contentType/contentEncoding
>>     In IPFS we do not store mime-types along with data, so we don't know it before data starts arriving. Public HTTP gateways are doing mime-type-sniffing and we will have to do the same in browser.
>>     Question: is it possible for Firefox to provide access to its own mime-type-sniffer? Perhaps setting contentType to auto or null could enable already existing heuristics described here?
>>     Reusing it would be more elegant than doing mime-sniffing in userland.
> 
> I believe omitting `contentType` / `contentEncoding` would do exactly that.

Feedback from battlefield: while it is ok to omit `contentEncoding`, I get [browser crash](https://user-images.githubusercontent.com/157609/42819665-7d643384-89d4-11e8-8e67-f63dbe3f4b82.png) if I don't include `contentType`. 

### Steps to reproduce 

0. Checkout  current HEAD (c36533ec7aa22dfae8cf7ff4e33eafaafb133ed1) and grab yesterday's Nightly 63.0a1
1. Comment out this line: https://github.com/mozilla/libdweb/blob/c36533ec7aa22dfae8cf7ff4e33eafaafb133ed1/demo/protocol/protocol.js#L19
2. `yarn && yarn demo:protocol`
3. Open `dweb://crash`
4. Nightly dies: 
    > ![browser crash](https://user-images.githubusercontent.com/157609/42819665-7d643384-89d4-11e8-8e67-f63dbe3f4b82.png)

**Comment by Gozala** [comment]
@lidel Thanks for reporting. I'll look into this
