### ISSUE TITLE
Request headers support for protocols

### ISSUE THREAD

**Issue by Gozala** [mozilla/libdweb#36]
This is followup from #2 where you can find all the details. Below quote is short summary:

> **Request Headers** - Things seems here sadly far more complicated, but it is also clear that this is really important for proper support of Video / Audio tags that just assume HTTP backend. It was suggested to me to that we could do following:
   - Plain data from request so that protocol handler can parse HTTP headers or alternative encoding of metadata.
    - Expose existing HTTP parser so it could be used. There was quite a reluctance on this though for reasons I did not understand (Part of it was that it's written in C++ and could not be easily extracted for just parsing use). It was highly recommended to instead just support more strictly encoded subset of the headers as anything send from video / audio tags would fit.

   Unfortunately it seems that supporting request headers would require C++ work and landing corresponding changes into Firefox which is to say it's likely going to take a while and likely will come after we illustrated that people are actually building on this work.

**Comment by lidel** [comment]
Is analog to HTTP's  [Range requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests) tracked under this, or should I create a separate issue for it?

**Comment by Gozala** [comment]
> Is analog to HTTP's Range requests tracked under this, or should I create a separate issue for it?

Let's track it here for now, depending how it will pan out I might need separate one, but for now it's good. One thing that could help is an example that produces Range requests that are disregarded.

**Comment by lidel** [comment]
@Gozala I  believe seeking with `<video>` is the most popular use for range requests right now. 

I created a small sandbox illustrating current problems, more details in README at:

- [lidel/libdweb/tree/video-range-use-case-demo](https://github.com/lidel/libdweb/tree/video-range-use-case-demo/demo/protocol#dweb-range-request-sandbox)

**Comment by Gozala** [comment]
Migrate to https://bugzilla.mozilla.org/show_bug.cgi?id=1572215
