### ISSUE TITLE
Demo Idea: Classroom Helper

### ISSUE THREAD

**Issue by soapdog** [mozilla/libdweb#46]
# Objective

Create a pair of Add-ons, one for the teacher, another for students, for helping educational activities in a classroom such as guided browsing, chatting, polling/quiz.

## Teacher Add-on
The teacher would be able to do the following actions:

* Open an URL in one, a subset, or all students machine.
* Send and reply to questions from students (privately).
* Participate in group chat.
* Highlight part of a page for the students.
* Check which students are present.
* Send polls/questions to all students.

## Student Add-on
The students would be able to:

* Chat with each other.
* Send questions to the teacher.
* Answer polls/quiz.

# Suggested usage of Libdweb APIs:

* Use [UDP](https://github.com/mozilla/libdweb/issues/4) for:
  * discovering peers on the network.'
  * multicasting messages to a group chat.
  * open the same page on all machines.
  * send info to highlight some element on the page.
  * check who is on class
* Use [TCP](https://github.com/mozilla/libdweb/issues/5) for:
  * Interact directly with the teacher.
 * Reply to poll/quiz 

# Suggested strategy
Programming this should be easy, the hardest part is actually building a good UX that is pleasant and gets out of the way. A [background script](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Anatomy_of_a_WebExtension#Background_scripts) could handle peering and presence check, opening pages. A [Sidebar](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/sidebarAction) can be used for the chat. A new tab with a [content script](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_scripts) can handle the interaction with the teacher. A [browser action](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserAction) with a popup menu with the possible actions for each role can be the main entry point for the add-on. [WebExtension storage](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage) can be used to save student data.

**Comment by Gozala** [comment]
I think demos and experiments are better explored in a separate repository. I'm not sure if https://github.com/libdweb/class-room is the right place for that but it's better than here.
