### ISSUE TITLE
TCP Socket

### ISSUE THREAD

**Issue by Gozala** [mozilla/libdweb#5]
In fact there was an effort to standardize [TCP and UDP Socket APIs][tcp-udp-sockets] which might be worth pursuing in this context. Firefox has scriptable [nsIServerSocket][] and [nsISocketTransportService][] that could be wrapped and exposed to WebExtensions.

# [🐞 1247628](https://bugzilla.mozilla.org/show_bug.cgi?id=1247628)

[tcp-udp-sockets]:https://www.w3.org/TR/tcp-udp-sockets/
[mozTCPSocket]:https://developer.mozilla.org/en-US/docs/Archive/B2G_OS/API/TCPSocket
[nsIServerSocket]:https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIServerSocket
[nsISocketTransportService]:https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsISocketTransportService

**Comment by autonome** [comment]
"Expose WebIDL TCPSocket to chrome code" - https://bugzilla.mozilla.org/show_bug.cgi?id=1207090

https://searchfox.org/mozilla-central/source/dom/network/tests/

**Comment by Gozala** [comment]
I run into TCPServerSocket bug, starting a server on the port that is already in use does not seem to report an issues but such socket seems to be corrupt. Filed [Bug 1057538](https://bugzilla.mozilla.org/show_bug.cgi?id=1057538)

**Comment by Gozala** [comment]
Status update here had being long due, so here it is:

- I have a #15 that was pretty much exposing existing implementations (made for Firefox OS) that is exposed through [TCPServerSocket.webidl](https://github.com/mozilla/gecko-dev/blob/86897859913403b68829dbf9a154f5a87c4b0638/dom/webidl/TCPServerSocket.webidl) / [TCPSocket.webidl](https://github.com/mozilla/gecko-dev/blob/86897859913403b68829dbf9a154f5a87c4b0638/dom/webidl/TCPSocket.webidl)
- Unfortunately as I was testing that implementation I discovered [Bug 1474150](https://bugzilla.mozilla.org/show_bug.cgi?id=1474150) - starting a server bound to a port that is already in use does not seem to report an issues and socket just seems to not work. There might be more issues along those lines.
- I end up working on alternative implementation #17 that pretty much ports [TCPSocket.cpp](https://github.com/mozilla/gecko-dev/blob/f51c4fa5d92d59fcb46f314e94edbf045cb3067c/dom/network/TCPSocket.cpp#L411) / [TCPServerSocket.cpp](https://github.com/mozilla/gecko-dev/blob/f51c4fa5d92d59fcb46f314e94edbf045cb3067c/dom/network/TCPServerSocket.cpp) (that are implementations of above mentioned webidl's) to JS + all the same stuff to expose this to add-ons.
- TCP API unlike other APIs had unique challenge _(it’s surprising other APIs were free of it)_ of having to deal with references across two privileged / unprivileged JS environments. More specifically for connections received on server socket we don't want to store references in privileged context as we won't know when to release them.
- GC issue lead me to spend more time figuring out how we could pass handles (which are objects rather than primitives) to the non-privileged JS so that privileged one could use them as keys in weak map. Which with some help I was able to work out.
- Non primitive handles also provides an opportunity for a nicer API that does not require defining everything as static method. Although I'm not entirely how much do people care, discussion in #8 suggests static APIs  were more desired.
- Ideally APIs will just match [w3 tcp-udp-sockets](https://www.w3.org/TR/tcp-udp-sockets/), but again lack of Readable / Writable does not make it viable option for now.
