### ISSUE TITLE
Cancel discovery?

### ISSUE THREAD

**Issue by alanshaw** [mozilla/libdweb#65]
Is there a way to cancel service discovery?

In the IPFS Companion web extension you can toggle between using an embedded IPFS node or talking to an external node (a daemon running on your laptop for example).

When toggling between embedded -> external the embedded node will be using `ServiceDiscovery` but we need to shut down the node as it's not going to be used anymore.

Currently I can set a flag and break out of the loop when the next discovered service is found/lost, but that could be a long time! Is there a way to end discovery immediately?

**Comment by Gozala** [comment]
@alanshaw you can always do something like:

```
const maybeNext = await Promise.race(cancelPromise, discovery.next())
if (maybeNext === CANCEL) {
  await discovery.return()
}
```

P.S.: Breaking out of the await loop does `.return()` call.

**Comment by Gozala** [comment]
I guess you don't even need to race with timeout you could still have a loop but then call `discovery.return()` to break it from outside.

**Comment by Gozala** [comment]
I'll close this but feel free to reopen if response was not satisfactory.
