### ISSUE TITLE
Promise rejection value is a non-unwrappable cross-compartment wrapper.

### ISSUE THREAD

**Issue by alanshaw** [mozilla/libdweb#67]
I believe I've only seen this happen on Linux and not macOS. I use the reload extension link:

<img width="254" alt="screen shot 2018-08-15 at 16 52 46" src="https://user-images.githubusercontent.com/152863/44158285-3d6a5d00-a0ac-11e8-8fdb-8674aff35849.png">

...and get the following errors:

<img width="892" alt="screen shot 2018-08-15 at 16 59 18" src="https://user-images.githubusercontent.com/152863/44158510-bb2e6880-a0ac-11e8-8efa-384bd5ab8d0f.png">

I took out the module I'm using for TCP and I no longer get the error, so I originally thought it was something to do with trying to bind to the same port twice...but the errors above look like it comes from the service discovery code.

**Comment by Gozala** [comment]
@alanshaw unfortunately I don't get enough context from the description to tell which promise (returned by which function) is to blame. I did pin down one case that #71 addresses but I'm not sure if that is the same one.

If it still occurs with latest changes please reopen, if you are able to tell which API function is that promise from that would really help. I also suspect that error would still occur it's just it won't be an unwrappable wrapper. To fix the actual error we'll need preferable more isolated example that I can reproduce.

**Comment by alanshaw** [comment]
I didn't have a lot of time to put that issue together yesterday and consequently it wasn't as detailed as I'd liked. I'll try out the latest fixes and pin down the function causing the issue if it still exists. Thank you 👍
