### ISSUE TITLE
Bluetooth API

### ISSUE THREAD

**Issue by willemneal** [mozilla/libdweb#81]
From what I've gleaned from Mozilla's documentation it seems there is some access to bluetooth, but it's limited and doesn't work for mobile.

Regardless, I'm interested in the possibility of using bluetooth as a meshnet and wonder your thoughts on it.

**Comment by lidel** [comment]
IPFS/libp2p projects are interested in adding Bluetooth transport.

There seems to be an Emerging Web Spec by [Web Bluetooth Community Group](https://www.w3.org/community/web-bluetooth/):

> Most of our activity happens in our [GitHub repository](https://github.com/WebBluetoothCG/web-bluetooth), with supporting code in adjacent repositories in the [WebBluetoothCG GitHub organization](https://github.com/WebBluetoothCG).


- https://github.com/WebBluetoothCG/web-bluetooth
- https://www.w3.org/community/web-bluetooth/
- https://webbluetoothcg.github.io/web-bluetooth/

It does not seem to be ready yet:

- According to MDN only Chromium-based browsers support proposed Web Bluetooth Spec: https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API#Browser_compatibility
- Mozilla Position on an Emerging Web Specification: https://github.com/mozilla/standards-positions/issues/95 and [bugzilla/674737#c13](https://bugzilla.mozilla.org/show_bug.cgi?id=674737#c13):
  > WebBluetooth API implementation in Gecko is suspended now, since Platform team regards the API 1) has security problem [1] and 2) is low priority. You may use the non-standard API [2] in Gecko already.
  > 
  > [1] https://github.com/WebBluetoothCG/web-bluetooth/issues/46
  > [2] https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS/API/Bluetooth_API#Gatt_interfaces

I imagine @willemneal  means the non-standard Gecko API from [[2]](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS/API/Bluetooth_API), yes?

@Gozala any thoughts on how feasible it would be to expose it via libdweb?

**Comment by Gozala** [comment]
From what I can tell by searching in the Firefox repo there's no implementation of it in the tree https://github.com/mozilla/gecko-dev/search?l=C%2B%2B&q=bluetooth

Which suggests me that either:

1. API never landed to Firefox and was Firefox OS only.
2. It was backed out after Firefox OS got discontinued.

Either way there I don't see a reasonable way of exposing it via libdweb.

**Comment by autonome** [comment]
It was Firefox OS only, and removed from mozilla-central when the B2G
codebase was removed.

Following along here is best place to see Mozilla's position on the
standards part: https://github.com/mozilla/standards-positions/issues/95

If you're interested in experimenting, here's Servo's Bluetooth
implementation: http://szeged.github.io/servo/

**Comment by Gozala** [comment]
I would love Bluetooth API but I'm afraid it's unrealistic to get it out without a larger Firefox support. Closing this issue in an effort to migrate issues to bugzilla & code into gecko.
