### ISSUE TITLE
Streams API

### ISSUE THREAD

**Issue by lgrahl** [mozilla/libdweb#86]
I know, I know, this is early work. But I suggest to strongly consider using the [streams API](http://streams.spec.whatwg.org/), at least for files and TCP streams.

**Comment by lidel** [comment]
Makes sense, given the fact [streams are now enabled in Firefox Nightly](https://user-images.githubusercontent.com/157609/49702075-c88bd780-fbf4-11e8-8c29-40d3e636829f.png) :ok_hand: :eyes: 
Ref. https://bugzilla.mozilla.org/show_bug.cgi?id=1389628

**Comment by Gozala** [comment]
That was always the goal, it's just streams were not available back when this was started.

**Comment by Gozala** [comment]
As a part of [migration to a gecko](https://bugzilla.mozilla.org/show_bug.cgi?id=libdweb) code base all APIs are converted to use `ReadableStreams`. As of `WritableStream` we still don't have them in spider-monkey so it will have to wait until we do.

Closing this in an effort to migrate all issues to bugzilla & code to gecko.
