### ISSUE TITLE
demo:protocol -- error opening input stream

### ISSUE THREAD

**Issue by cmarxer** [mozilla/libdweb#89]
I cloned libdweb and want to test the protocol API demo on Firefox Nightly (67.0a1 (2019-02-09) (64-bit)):
`$ web-ext run --firefox=/Applications/Firefox\ Nightly.app/Contents/MacOS/firefox-bin  --browser-console --url about:debugging --source-dir demo/protocol`

At first there is now sign that loading the extension failed, but calling for instance `dweb://hello/world` fails (I am forwarded to duckduckgo which is my default search engine).

On the browser console I get this error which seems to be related to the extension:
`uncaught exception: Error opening input stream (invalid filename?): file:///Users/dmir/software/libdweb/src/protocol/client.js`
I carefully checked, the file exists in my file system. Any ideas what is going wrong?

**Comment by sammacbeth** [comment]
You need to disable the content sandbox in Firefox. You can put `env MOZ_DISABLE_CONTENT_SANDBOX=1` before your `web-ext` command to do this.

**Comment by cmarxer** [comment]
Thank you, setting environment variable `MOZ_DISABLE_CONTENT_SANDBOX` to `1` solves the issue.
