### ISSUE TITLE
[Question] udp multicast discovery

### ISSUE THREAD

**Issue by mcosmin222** [mozilla/libdweb#91]
Hello,

I have a media player application which exposes a remote control interface on the local network. It works by joining an udp multicast group and advertise its presence there. Other instances of the app can detect its presence and act as a remote controller.

Now i want to extand this to http. While it has a http based interface, it is difficult to use it as you need to know the host name in advance.

What I want to do is create a browser extension, which will join that multicast group and listen on the traffic. And just that. It won't broadcast by itself. Then the extension will present an list of active instances on the network, and the user can choose from the list, thus solving the hostname problem. Futher communication will be done via tcp.

My question is: is this possible using this library? Basically, i want to join a specific multicast group. I have eye balled the API, but i can't see how to set the port on which service discovery is done (i used a different multicast group than DNS).

**Comment by Gozala** [comment]
@mcosmin222 it appears to me that you want to use [dns-sd API](https://github.com/mozilla/libdweb/blob/master/Readme.md#service-discovery-api) as a [standardized way](https://tools.ietf.org/html/rfc6763) to do exactly that.
